# `function` handle_exception
::: g2o.exception.handle_exception